version: '3.2'

volumes:
  static:
services:
  nginx:
    #image: nginx:stable
    #image: twalter/openshift-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - target: 8081
        published: 8081
        protocol: tcp
        mode: host
    depends_on:
      - gunicorn
    volumes:
      #- "static:/usr/share/nginx/html/static"
      - type: volume
        source: static
        target: /usr/share/nginx/html/static
    labels:
      kompose.service.expose: "true"
      kompose.volume.size: 1Gi
      app: facebook-django-mock
  gunicorn:
    #image: python:3.6-slim
    build:
      context: ./gunicorn
      dockerfile: Dockerfile
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    volumes:
      #- "static:/app/static"
      - type: volume
        source: static
        target: /app/static
    labels:
        app: facebook-django-mock
    depends_on:
      - db
  db:
    image: mysql:5.7
    #image: registry.access.redhat.com/rhscl/mysql-57-rhel7
    #command: --default-authentication-plugin=mysql_native_password
    #restart: always
    environment:
      MYSQL_DATABASE: facebook_django_mock
      MYSQL_USER: equestrin
      MYSQL_PASSWORD: pija
      MYSQL_ROOT_PASSWORD: uwu
    labels:
        app: facebook-django-mock
  adminer:
    image: adminer
    #restart: always
    ports:
      - target: 8080
        published: 8001
        protocol: tcp
        mode: host
    depends_on:
      - db
    labels:
        app: facebook-django-mock