version: '3.2'

volumes:
  static:
services:
  nginx:
    #image: nginx:stable
    #image: twalter/openshift-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - target: 8081
        published: 8081
        protocol: tcp
        mode: host
    depends_on:
      - gunicorn
    volumes:
      #- "static:/usr/share/nginx/html/static"
      - type: volume
        source: static
        target: /usr/share/nginx/html/static
    labels:
      kompose.service.expose: "true"
      kompose.volume.size: 1Gi
      app: facebook-django-mock
  gunicorn:
    #image: python:3.6-slim
    build:
      context: ./gunicorn
      dockerfile: Dockerfile
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    volumes:
      #- "static:/app/static"
      - type: volume
        source: static
        target: /app/static
    labels:
        app: facebook-django-mock
    depends_on:
      - db
  db:
    image: postgres
    #restart: always
    environment:
      POSTGRES_PASSWORD: uwu
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host
  adminer:
    image: adminer
    #restart: always
    ports:
      - target: 8080
        published: 3306
        protocol: tcp
        mode: host
    depends_on:
      - db