apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: adminer
    app: facebook-django-mock
  name: adminer
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: adminer
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
