apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: gunicorn
  name: gunicorn
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: gunicorn
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
