apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: gunicorn
  name: gunicorn
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: python:3.6-slim
    generation: null
    importPolicy: {}
    name: 3.6-slim
status:
  dockerImageRepository: ""
