apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    app: facebook-django-mock
    kompose.cmd: kompose convert --provider openshift -o openshift-config/
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: gunicorn
  name: gunicorn
spec:
  replicas: 1
  selector:
    io.kompose.service: gunicorn
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: gunicorn
    spec:
      containers:
      - image: ' '
        name: gunicorn
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /app/static
          name: static
      restartPolicy: Always
      volumes:
      - name: static
        persistentVolumeClaim:
          claimName: static
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - gunicorn
      from:
        kind: ImageStreamTag
        name: gunicorn:latest
    type: ImageChange
status: {}
