apiVersion: v1
kind: Service
metadata:
  annotations:
    app: facebook-django-mock
    kompose.cmd: kompose convert --provider openshift -o openshift-config/ -v
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: gunicorn
  name: gunicorn
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    io.kompose.service: gunicorn
status:
  loadBalancer: {}
