# Generated by Django 2.1.3 on 2018-11-23 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_mock', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
